Add files via upload
YerongAI/Office-Tool pull request #624
Opened 2023-02-21 14:39 UTC by VenusGirl

Korean Products Name

2023-02-21 14:42 UTC, YerongAI requested changes

2023-02-21 14:42 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/ProductsName/ko-kr.xaml
> +    <sys:String x:Key="StandardSPLA2021Volume">Office LTSC Standard 2021 (SPLA)&#x200e; - 볼륨 라이선스</sys:String>
`&#x200e;` can be removed.

2023-02-21 14:42 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/ProductsName/ko-kr.xaml
> +    <sys:String x:Key="ProPlusSPLA2021Volume">Office LTSC Professional Plus 2021 (SPLA)&#x200e; - 볼륨 라이선스</sys:String>
`&#x200e;` can be removed.

2023-02-21 14:42 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/ProductsName/ko-kr.xaml
> +    <sys:String x:Key="O365HomePremRetail">Microsoft 365 (가족 및 개인)&#x200e;</sys:String>
`&#x200e;` can be removed.

2023-02-21 15:38 UTC, VenusGirl reviewed
Fixed

2023-02-21 15:47 UTC, VenusGirl reviewed
Fixed

2023-02-22 13:31 UTC, YerongAI approved these changes

2023-02-22 13:31 UTC, merged