Update german translation for V10.1.2
YerongAI/Office-Tool pull request #658
Opened 2023-04-09 15:19 UTC by Henry2o1o

2023-04-10 04:17 UTC, YerongAI requested changes
Please check all access keys and change them if needed.

2023-04-10 04:17 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/Languages/de-de.xaml
> +    <sys:String x:Key="Activate_Uninstall_Unactivated_Key">_Alle nicht aktivierten Schlüssel deinstallieren</sys:String>
The access key `A` is same as the next string, please change to other one if possible.

2023-04-10 04:17 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/Languages/de-de.xaml
> +    <sys:String x:Key="Activate_License_Collapse">_Alle einklappen</sys:String>
The access keys should be same as original. Such as `_Refresh` -> `Aktualisie_ren` and `_Expand all` -> `Alle _erweitern`. If not, you should set a new one according the rules: https://wpf-tutorial.com/control-concepts/access-keys/

2023-04-13 23:25 UTC, Berny23 commented
This translation attempt is terrible and has clearly been made via copy & paste from an online translator tool. 
Also, strings like "Lizenzen Liste", "Intervall erneuern:" or "Aktivierung Objektname:" are all literal translations which are grammatically incorrect and don't make any sense in context.

2023-04-14 00:12 UTC, iDolmatov commented
https://github.com/YerongAI/Office-Tool/commits/main/src/OfficeToolPlus/Dictionaries/Languages/de-de.xaml
The main translator has more priority and credibility. It makes sense to reject the pull request.

2023-04-14 04:13 UTC, YerongAI commented
As @Berny23 pointed out. The translation is not perfect yet.

Our projects are intended to provide quality translations to our users. If not, or if only machine translation is used, then our project loses its meaning.

We hope you can learn more from it and providing better quality translations in the future. Thanks.

2023-04-14 04:13 UTC, closed without merging