Korean Update
YerongAI/Office-Tool pull request #669
Opened 2023-04-15 11:16 UTC by VenusGirl

2023-04-15 14:16 UTC, YerongAI requested changes

2023-04-15 14:16 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/Languages/ko-kr.xaml
> +    <sys:String x:Key="Task_OSPP">OSPP가 작업 중, 잠시 기다려 주십시오.</sys:String>
The OSPP was removed.

2023-04-15 14:16 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/Languages/ko-kr.xaml
> -    <sys:String x:Key="Ques_Uninstall_Product_Key">이 제품 키를 제거하겠습니까?</sys:String>
The `Ques_Uninstall_Product_Key` is missing.

2023-04-16 03:58 UTC, yaeyaya commented
I think VenusGirl's translation is better cause it's original Korean, not the textbook-style or dictionary-style from me. 😆

2023-04-16 04:01 UTC, yaeyaya commented
@VenusGirl 님, 번역 내용을 수정하고 개선해서 감사해요. 저도 더 어울리는 번역을 배웠어요. ㅋㅋ

2023-04-16 09:13 UTC, YerongAI approved these changes

2023-04-16 09:14 UTC, merged