zh-TW update
YerongAI/Office-Tool pull request #823
Opened 2024-04-16 07:11 UTC by chiyi4488

2024-04-16 10:01 UTC, YerongAI requested changes

2024-04-16 10:01 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/Languages/zh-tw.xaml
> +    <sys:String x:Key="Deploy_Architecture_Current_Installed">目前安裝的 Office 架構; {0}。</sys:String>
冒号打成了分号。

2024-04-16 10:01 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/Languages/zh-tw.xaml
> +    <sys:String x:Key="Err_No_KMS_Lic">無法儲存 KMS 設定 (找不到有效的 KMS 授權)。</sys:String>
`無法儲存 KMS 設定，找不到有效的 KMS 授權。` 更符合习惯和要求。

2024-04-17 02:49 UTC, chiyi4488 commented on src/OfficeToolPlus/Dictionaries/Languages/zh-tw.xaml
> +    <sys:String x:Key="Err_No_KMS_Lic">無法儲存 KMS 設定 (找不到有效的 KMS 授權)。</sys:String>
我原本也打算這麼做，但因為之前翻的語句都是「，請 …」，因此在此處若「，找不到有效的 Office KMS 授權。」，似乎不太統一格式。

若以語句來說，亦不應該是用逗號，而是刪節號「無法儲存 KMS 設定—— 找不到有效的 Office KMS 授權。」但刪節號從來沒有在 Office Tool Plus 中使用過（不夠統一），故最後選擇用括號表現之。

@YerongAI 你覺得用刪節號會比較合適嗎？如何合適，就這麼改:)。

2024-04-17 02:54 UTC, chiyi4488 commented on src/OfficeToolPlus/Dictionaries/Languages/zh-tw.xaml
> +    <sys:String x:Key="Err_No_KMS_Lic">無法儲存 KMS 設定 (找不到有效的 KMS 授權)。</sys:String>
（BTW 少了Office 一詞，合併前會更正）

2024-04-17 09:03 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/Languages/zh-tw.xaml
> +    <sys:String x:Key="Err_No_KMS_Lic">無法儲存 KMS 設定 (找不到有效的 KMS 授權)。</sys:String>
弹窗信息属于另一个板块，某种意义上来说不存在上下文匹配，也就是可以不用关心上下文语境。

2024-04-18 10:50 UTC, YerongAI requested changes

2024-04-18 10:50 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/Languages/zh-tw.xaml
> +    <sys:String x:Key="Err_No_KMS_Lic">無法儲存 KMS 設定── 找不到有效的 Office KMS 授權。</sys:String>
前后空格不一致。

除此之外你还可以考虑换行表达，例如：

```text
無法儲存 KMS 設定。

错误：找不到有效的 Office KMS 授權。
```

2024-04-18 17:55 UTC, chiyi4488 commented on src/OfficeToolPlus/Dictionaries/Languages/zh-tw.xaml
> +    <sys:String x:Key="Err_No_KMS_Lic">無法儲存 KMS 設定── 找不到有效的 Office KMS 授權。</sys:String>
留一個空格是我的文書習慣，但我後來查詢了下中文破折號確實鮮少留一個空格在後的🤡

現在這份翻譯內好像也沒有 `\n` 的譯文，比起破折號，感覺它的破壞性比較大。

2024-04-19 10:26 UTC, YerongAI approved these changes

2024-04-19 10:26 UTC, merged