Create hu-hu.xaml
YerongAI/Office-Tool pull request #932
Opened 2024-12-27 16:49 UTC by JohnFowler58

Hungarian language file.

John Fowler

2024-12-28 05:18 UTC, YerongAI commented
No remarks need to be translated.

> <-- Country settings, it is used to get information from server. -->

Keep them in English, do not translate them.

2024-12-28 05:28 UTC, YerongAI requested changes

2024-12-28 05:28 UTC, YerongAI commented on src/OfficeToolPlus/Dictionaries/Languages/hu-hu.xaml
> +    <sys:String x:Key="Eula.Content">A szoftver használatával el kell fogadnia a [Szoftver licencfeltételeit] ({0}) és a [Microsoft szolgáltatási szerződést] ({1}).</sys:String>
Remove space between [] and (), this is markdown language format.

2024-12-28 05:29 UTC, YerongAI approved these changes

2024-12-28 05:29 UTC, merged

2024-12-29 09:32 UTC, JohnFowler58 commented
Dear YerongAI !

Thank you for fixing the Hungarian language file (hu-hu.xaml)!
I was away from my computer yesterday (family program).

Regards
John Fowler.